-- MySQL Script generated by MySQL Workbench
-- Wed Mar 21 23:47:43 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Transfert
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Transfert
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Transfert` DEFAULT CHARACTER SET utf8 ;
USE `Transfert` ;

-- -----------------------------------------------------
-- Table `Transfert`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transfert`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `LastName` VARCHAR(45) NOT NULL,
  `FirstName` VARCHAR(45) NULL COMMENT '	',
  `E-mail` VARCHAR(50) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Tel` VARCHAR(15) NOT NULL,
  `Address` VARCHAR(50) NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transfert`.`Receiver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transfert`.`Receiver` (
  `idReceiver` INT NOT NULL AUTO_INCREMENT,
  `LastName` VARCHAR(45) NOT NULL,
  `FirstName` VARCHAR(45) NULL,
  `Tel` VARCHAR(15) NULL,
  PRIMARY KEY (`idReceiver`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transfert`.`Transfert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transfert`.`Transfert` (
  `idTransfert` INT NOT NULL AUTO_INCREMENT,
  `Date_Transfert` DATETIME NOT NULL,
  `Amount` DECIMAL(18,0) NOT NULL,
  PRIMARY KEY (`idTransfert`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transfert`.`Partner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transfert`.`Partner` (
  `idPartner` INT NOT NULL AUTO_INCREMENT,
  `Parter_Name` VARCHAR(45) NOT NULL,
  `Location` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Tel` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idPartner`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
